name: Terraform APPLY Payments APP
on:
  workflow_dispatch:

jobs:
  terraform-apply-payments-app:
    uses: ./.github/workflows/templates/terraform-apply.yml
    with:
      app_name: 'pay-app'
    secrets: inherit