name: Terraform Destroy Production APP
on:
  workflow_dispatch:

jobs:
  terraform-destroy-production-app:
    uses: ./.github/workflows/templates/terraform_destroy.yml
    with:
      app_name: 'prod-app'
    secrets: inherit