name: Terraform Destroy Order APP
on:
  workflow_dispatch:

jobs:
  terraform-destroy-order-app:
    uses: ./.github/workflows/terraform_destroy.yml
    with:
      app_name: 'order-app'
#      AWS_REGION: ${{ secrets.AWS_REGION }}
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
    secrets: inherit

