name: Terraform Destroy Payments APP
on:
  workflow_dispatch:

jobs:
  terraform-destroy-payments-app:
    uses: ./.github/workflows/terraform_destroy.yml
    with:
      app_name: 'pay-app'
    secrets: inherit