name: Terraform APPLY Production APP
on:
  workflow_dispatch:

jobs:
  terraform-apply-payments-app:
    uses: ./.github/workflows/terraform-apply.yml
    with:
      app_name: 'prod-app'
    secrets: inherit