name: Terraform Destroy Order APP
on:
  workflow_dispatch:

jobs:
  terraform-destroy-order-app:
    uses: ./.github/templates/terraform_destroy.yml@develop
    with:
      app_name: 'order-app'
    secrets: inherit

